stages:
  - build

build-fedora:
  stage: build
  image: registry.fedoraproject.org/fedora:latest
  before_script:
    - dnf builddep -y *.spec
  script:
    - make

build-tito-rpm:
  stage: build
  image: registry.fedoraproject.org/fedora:latest
  before_script:
    - dnf install -y tito
    - dnf builddep -y *.spec
  script:
    - tito build --test --rpm
